Fixed Vue warns missing end tag + invalid end tag when in Softwareverwaltung-Tab
- Template compilation error: Element is missing end tag
-Template compilation error: Invalid end tag